# Move base node parameters. For full documentation of the parameters in this file, please see
#
# http://wiki.ros.org/costmap_2d
# http://wiki.ros.org/navigation/Tutorials/RobotSetup
#
local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0 #50
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 10
  height: 10
  resolution: 0.05
  transform_tolerance: .2000
  inflation_radius: 0.01
  cost_scaling_factor: 10