# Move base node parameters. For full documentation of the parameters in this file, please see
#
# http://www.ros.org/wiki/move_base
# http://wiki.ros.org/navigation/Tutorials/RobotSetup
#
shutdown_costmaps: false

# Local Update Loop
controller_frequency: 20.0 
controller_patience: 3.0 

# Global Update Loop
planner_frequency: 20.0   
planner_patience: 5.0 

oscillation_timeout: 10.0
oscillation_distance: 0.2
